include(
    ":app",
    ":common-ui",
    ":core:navigation",
    ":core:utils",
    ":core:rx",
    ":core:errors",
    ":core:database",
    ":feature:chat_core",
    ":feature:chat_main",
    ":feature:profile_settings"
)