include(
    ":app",
    ":common-ui",
    ":core:navigation",
    ":core:utils",
    ":domain:domain-core",
    ":data:data-local",
    ":data:data-core",
    ":feature:chat_core",
    ":feature:chat_main",
    ":feature:profile_settings"
)